[package]
name = "kinematics"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "example"


[dependencies]
libm = "0.2.2"
terminal_size = "0.1.17"
dialoguer = "0.10.1"