on: [push]

name: ARMv7 build


jobs:
  build_and_test:
    name: Linux x86-64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
    # Artifact name
            name: Linux x86-64
    # A file, directory or wildcard pattern that describes what to upload
            path: target/release/example
    # The desired behavior if no files are found using the provided path.
  linux_arm7:
    name: Linux ARMv7
    runs-on: ubuntu-latest
    env:
       RUSTFLAGS: -C target-feature=+crt-static
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: armv7-unknown-linux-gnueabihf
          override: true
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --target armv7-unknown-linux-gnueabihf --release
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
    # Artifact name
            name: Linux ARMv7
    # A file, directory or wildcard pattern that describes what to upload
            path: target/armv7-unknown-linux-gnueabihf/release/example
  win_x86-64:
    name: Windows x86-64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-pc-windows-gnu
          override: true
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --target x86_64-pc-windows-gnu --release
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
    # Artifact name
            name: Windows x86-64
    # A file, directory or wildcard pattern that describes what to upload
            path: target/x86_64-pc-windows-gnu/release/example.exe
